# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48aa7eed1d9e7412f3102485718d6208ad105a9bb2b650570c5cd9e1301297901f4023676914718e8fa4361b833f291a53a74d619d1069adaa169dcd0c6755ef

test:
  secret_key_base: 20ab91eff9ce508e8d624b1962c0c6ef531745a2f4076ad8e0b0c8f988404b26e8d98a5031fabc2667f9d92a4754fd17a384017f636f90f714375b9cd4d790d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
